name: social_network_test
description: A new Flutter social media application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_vector_icons: ^1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.23.0+1
  http: ^0.13.4
  curved_navigation_bar: ^1.0.1
  carousel_slider: ^4.0.0
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  material_design_icons_flutter: ^5.0.6595
  flutter_spinkit: ^5.1.0
  velocity_x: ^3.3.0
  get: ^4.6.1

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#fffacd"
  image: assets/images/nearLogos/noMargin/icon_nm.png
  color_dark: "1e2040"
  image_dark: assets/images/nearLogos/noMargin/icon_wht_nm.png
  android: true
  ios: true


  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.9.2

flutter_icons:
   image_path: "assets/icons/icon.png"
   android: true
   ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/images/JEPH.png
    - assets/images/avatar-1300331_640.png
    - assets/images/laptop-336373_640.jpg
    - assets/images/Copia de JEPH.svg
    - assets/images/Copia de JEPH.png
    - assets/images/google-round.png
    - assets/images/despaired-2261021_640.jpg
    - assets/images/JEPH (1).gif
    - assets/images/train-797072_640.jpg
    - assets/images/JEPH (1).svg
    - assets/images/miniature-figure-1745770_640.jpg
    - assets/images/JEPH (1).png
    - assets/images/office-620822_640.jpg
    - assets/images/JEPH.gif
    - assets/images/JEPH.svg
    - assets/icons/icon.png
    - assets/icons/45615215.png
    - assets/icons/
    - assets/images/nearLogos/near_icon.svg
    - assets/images/nearLogos/near_icon_wht.svg
    - assets/images/nearLogos/near_logo.svg
    - assets/images/nearLogos/near_logo_stack.svg
    - assets/images/nearLogos/near_logo_stack_wht.svg
    - assets/images/nearLogos/near_logo_wht.svg
    - assets/images/nearLogos/near_type.svg
    - assets/images/nearLogos/near_type_wht.svg
    - assets/images/nearLogos/noMargin/icon_nm.svg
    - assets/images/nearLogos/noMargin/icon_wht_nm.svg
    - assets/images/nearLogos/noMargin/logo_nm.svg
    - assets/images/nearLogos/noMargin/logo_stack_nm.svg
    - assets/images/nearLogos/noMargin/logo_stack_wht_nm.svg
    - assets/images/nearLogos/noMargin/logo_wht_nm.svg
    - assets/images/nearLogos/noMargin/type_nm.svg
    - assets/images/nearLogos/noMargin/type_wht_nm.svg
    - assets/images/Image (69).jpg
    - assets/images/nearLogos/noMargin/icon_wht_nm.png


  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
